# yaml-language-server: $schema=https://primadi.github.io/lokstra/schema/lokstra.schema.json

configs:
  dbpool-manager:
    use-sync: true
    dbpool-name: global-db
    heartbeat-interval: ${DBPOOL_MANAGER_HEARTBEAT_INTERVAL:5} # in minutes
    reconnect-interval: ${DBPOOL_MANAGER_RECONNECT_INTERVAL:5} # in seconds
    
named-db-pools:
  global-db:
    dsn: ${GLOBAL_DB_DSN:postgres://postgres:adm1n@localhost:5432/lokstra_db}
    schema: ${GLOBAL_DB_SCHEMA:lokstra_auth}